spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCh24LlLYiO1KonndXIno/uyKMLy1qvbf69iD5bpSPaIj3lBc3w1AprXC2VNR5xs0lb2rPl6/ZWpNeB5H1gTWIMB9sFtEzh6cPSgH+hFxX3ZzMfAbYh2gHCo04MJGdowXSg+bs3QvSFOiaCfG5F/9Y0gRY+O4GwI3hkRC/G7cuTR6ZDffRWtTr2NX/OvAPZQ5Ilq+18k2KP04vIoVsurlTv3rQaj5ucGfI/0kVZAT7QY1NXQTc6XoqN1i11qDFMCCRIrSEC7wQnOUOi7l3kn3PSKWo3PqERf4KChFv5kgtXhcQswhZJkoQRfCQ14GD5Mxo6f12DXs3AFxsoJgGBQKonL3Xi6m4mZeCY8BsuB8pXtI4OPemipBTvKIBIUfM9hO8='

gateway:
  ip: 172.18.0.4
  #ip: 192.168.0.14

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There's no item.
